from pathlib import Path
from datetime import datetime
from fpdf import FPDF

CERT_DIR = Path(__file__).resolve().parent.parent / "certificates"
CERT_DIR.mkdir(exist_ok=True)

class CertPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 20)
        self.cell(0, 12, "CourseHub", ln=1, align="C")
        self.set_font("Helvetica", "", 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "Learning Made Simple", ln=1, align="C")
        self.ln(4)
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, "Generated by CourseHub", 0, 0, "C")

def generate_certificate(student_name: str, course_title: str, date_issued: datetime, out_name: str = None) -> str:
    pdf = CertPDF(orientation="L", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 28)
    pdf.ln(10); pdf.cell(0, 18, "Certificate of Completion", ln=1, align="C")

    pdf.set_font("Helvetica", "", 14)
    pdf.ln(6); pdf.cell(0, 10, "This is to certify that", ln=1, align="C")

    pdf.set_font("Helvetica", "B", 24)
    pdf.ln(2); pdf.cell(0, 14, student_name, ln=1, align="C")

    pdf.set_font("Helvetica", "", 14)
    pdf.ln(2); pdf.cell(0, 10, "has successfully completed the course", ln=1, align="C")

    pdf.set_font("Helvetica", "B", 20)
    pdf.ln(2); pdf.cell(0, 12, f"\"{course_title}\"", ln=1, align="C")

    pdf.set_font("Helvetica", "", 12)
    pdf.ln(6); pdf.cell(0, 8, f"Issued on: {date_issued.strftime('%Y-%m-%d')}", ln=1, align="C")

    pdf.ln(16)
    left_x, right_x = 50, 240
    y = pdf.get_y() + 20
    pdf.line(left_x, y, left_x + 60, y)
    pdf.line(right_x - 60, y, right_x, y)
    pdf.set_y(y + 3); pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 6, "Instructor / Admin", align="L")
    pdf.set_x(right_x - 60); pdf.cell(60, 6, "CourseHub Director", align="R")

    safe_student = "".join(c for c in student_name if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")
    safe_course  = "".join(c for c in course_title if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")
    fname = out_name or f"certificate_{safe_student}_{safe_course}.pdf"
    out_path = CERT_DIR / fname
    pdf.output(str(out_path))
    return str(out_path)
