from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate
from reportlab.lib.units import inch

def get_pdf_styles():
    """Return commonly used ReportLab styles for PDF rendering."""
    styles = getSampleStyleSheet()

    heading = ParagraphStyle(
        "Heading",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=colors.HexColor("#000000"),
        alignment=1,  # center
        spaceAfter=20,
    )

    subheading = ParagraphStyle(
        "SubHeading",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#0B5394"),
        spaceBefore=10,
        spaceAfter=10,
    )

    body = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=16,
        textColor="#333333",
    )

    section = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=colors.HexColor("#0B5394"),
        spaceBefore=12,
        spaceAfter=10,
    )

    return heading, subheading, body, section


def create_doc(filename):
    return SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )


def header_footer(canvas, doc):
    """Reusable footer for all PDFs."""
    canvas.saveState()
    canvas.setLineWidth(0.5)
    canvas.line(inch, 11.15 * inch, 7.5 * inch, 11.15 * inch)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(7.5 * inch, 0.6 * inch, "Generated by Amwaj — © 2025")
    canvas.restoreState()
